wix/wix-ui-tpa

src/baseComponents/ErrorMessageWrapper/ErrorMessageWrapper.tsx, src/components/Input/Input.tsx, src/components/Input/README.md, src/components/Input/index.tsx, stories/Input/InputExtendedExample.st.css, stories/Input/InputExtendedExample.tsx, stories/Input/index.tsx
deleted the use of withStylable
update README
overriding the colors only when the user change the color
=> update Input implementation

package.json
=> added fix flag to yoshi lint

mocks/fakeTPANumberChange.json, src/components/Divider/Divider.st.css, src/components/Divider/Divider.tsx, src/components/Divider/index.tsx, stories/Divider.story.tsx, stories/Divider/DividerExtendedExample.st.css, stories/Divider/DividerExtendedExample.tsx, stories/Divider/index.tsx, stories/helperComponents/NumberPicker.scss, stories/helperComponents/NumberPicker.tsx, stories/index.tsx
implemented divider component with style override capabilities
=> divider component

src/components/Divider/Divider.st.css, stories/Divider/DividerExtendedExample.st.css
removed unnecessary calls to style-processor color/unit
=> divider css refactoring

src/components/Button/Button.driver.ts, src/components/Button/Button.e2e.ts, src/components/Button/Button.spec.tsx, src/components/Button/Button.st.css, src/components/Button/Button.tsx, src/components/Button/README.md, src/components/Button/index.tsx, src/components/Button/mixins.js, src/testkit/enzyme.ts, src/testkit/index.ts, src/testkit/protractor.ts, stories/Button.story.tsx, stories/Button/ButtonExtendedExample.st.css, stories/Button/ButtonExtendedExample.tsx, stories/Button/index.tsx, stories/index.tsx
added overridable button component
=> Button component

package.json
make the `teamcity-surge-autorelease` run even if the build fails.
also, reorder some steps
=> infra: refactor build step

src/components/Input/Input.st.css, stories/Input/InputExtendedExample.st.css, stories/Input/index.tsx
added the ability to customise the font of Input component
=> dev: input font customisation

stories/Button.story.tsx
removed children props from button story
=> fix: button story

stories/helperComponents/MockSettings.scss, stories/helperComponents/MockSettings.tsx
display color picker vertical layout
=> dev: Mock settings display color picker vertically

src/components/Text/README.md, src/components/Text/Text.spec.tsx, src/components/Text/Text.st.css, src/components/Text/constants.ts
Hi Shlomi 
I added new theme to text. 
I also fixed the readme which had wrong properties.
@liorMar
=> Bookings - add new theme for text

src/components/Text/Text.spec.tsx, src/components/Text/Text.st.css, src/components/Text/constants.ts
Hey, please review and merge, shouldn't be any different than other typos
=> added text typography - running text 2

mocks/fakeTPAChange.json, src/components/Button/Button.st.css, src/components/Divider/Divider.st.css, src/components/Text/Text.spec.tsx, stories/helperComponents/MockSettings.tsx
=> allowing to receive 0 as valid width/radius value

package.json, src/components/Tabs/README.md, src/components/Tabs/Tabs.driver.ts, src/components/Tabs/Tabs.e2e.ts, src/components/Tabs/Tabs.protractor.driver.ts, src/components/Tabs/Tabs.spec.tsx, src/components/Tabs/Tabs.st.css, src/components/Tabs/Tabs.tsx, src/components/Tabs/constants.ts, src/components/Tabs/index.tsx, src/testkit/enzyme.ts, src/testkit/index.ts, src/testkit/protractor.ts, stories/Tabs.story.tsx, stories/Tabs/TabsExtendedExample.st.css, stories/Tabs/TabsExtendedExample.tsx, stories/Tabs/index.tsx, stories/index.tsx
=> Add tabs component

src/components/Button/Button.st.css, src/components/Card/Card.st.css, src/components/Card/README.md, src/components/Card/docs/CardExtendedExample.tsx, src/components/OverlappingCard/README.md, src/components/OverlappingCard/docs/OverlappingCardExtendedExample.tsx
fix medium button padding
fix card media default background color
fix image of story examples
=> fix defaults to Card and Button

src/components/Button/Button.driver.ts, src/components/Button/Button.spec.tsx, src/components/Button/Button.st.css, src/components/Button/Button.tsx, stories/Button.story.tsx, stories/Button/ButtonExtendedExample.st.css, stories/Button/ButtonExtendedExample.tsx, stories/helperComponents/MockSettings.tsx
until now the border grow outside the button area and made the button dimensions bigger than the design system specs
added support to full width (required for mobile view)
=> button improvement

generator/codemods/index.js, generator/codemods/stories-file.js, generator/templates/src/components/Component/Component.driver.ts, generator/templates/src/components/Component/Component.e2e.ts, generator/templates/src/components/Component/Component.protractor.driver.ts, generator/templates/src/components/Component/Component.spec.tsx, generator/templates/src/components/Component/Component.st.css, generator/templates/src/components/Component/Component.tsx, generator/templates/src/components/Component/README.md, generator/templates/src/components/Component/index.tsx, generator/templates/stories/Component.story.tsx, generator/templates/stories/Component/ComponentExtendedExample.st.css, generator/templates/stories/Component/ComponentExtendedExample.tsx, generator/templates/stories/Component/index.tsx, package.json
introducing component generator for `wix-ui-tpa`!
just `npm run generate` or (use wuf cli directly with `wuf generate`)
---
`npm run generate`:
1. will ask for a mandatory component name
1. will ask for and optional description.
1. will scaffold component according to template in `generators/templates`
1. will run any codemods set in `generators/codemods`
1. profit ;)
=> include component generator from wix-ui-framework

src/components/TPAComponentsConfig/TPAComponentsConfig.tsx, src/components/Tabs/Tabs.spec.tsx, src/components/Tabs/Tabs.st.css, src/components/Tabs/Tabs.tsx, src/components/Tabs/TabsUI.tsx, stories/Tabs/TabsMobileExample.tsx, stories/Tabs/index.tsx
using flex in this situation caused some bugs in webkit.
Moved implementation to simpler css.
=> fix tabs - remove flex from component's css

src/components/Button/Button.st.css, stories/Button/ButtonExtendedExample.st.css, stories/Button/ButtonExtendedWithStyleParamsExample.st.css, stories/Button/ButtonExtendedWithStyleParamsExample.tsx, stories/Button/index.tsx
Like this PR but for `border-width`:
https://github.com/wix/wix-ui-tpa/pull/84
=> button: don't add "px" to border width

src/components/StripCard/StripCard.st.css
after a session of our ux and Johanna Asseraf from the design system they decide to remove the margin-top
=> (StripCard) removed margin top from media container

package.json
storybook new version 5.1.0 have breaking changes
=> anchored storybook version.

src/components/Card/Card.st.css, src/components/Card/README.md, src/components/Card/docs/CardExtendedExample.st.css, src/components/Card/docs/exampleWithSettingPanel.tsx, src/components/OverlappingCard/OverlappingCard.st.css
added multiple background colors to Media container
https://zeroheight.com/7sjjzhgo2/p/19342a/b/247036
=> (Card | OverlappingCard) Media container with multiple background colors

src/components/Card/Card.st.css, src/components/Card/README.md, src/components/Card/docs/CardExtendedExample.st.css, src/components/Card/docs/exampleWithSettingPanel.tsx, src/components/OverlappingCard/OverlappingCard.st.css
=> Revert "(Card | OverlappingCard) Media container with multiple background colors"

src/components/Tabs/Tabs.st.css
=> fix tabs shadow border bleed issue

.prettierignore, package.json, tslint.json
- Add prettier
- Exclude autogenerated testkit files
- Add automatic linting before commit
=> Improve linting flow

src/components/Tabs/ScrollableTabs/ScrollableTabs.st.css, src/components/Tabs/ScrollableTabs/ScrollableTabs.tsx, src/components/Tabs/Tabs.st.css, src/components/Tabs/Tabs.tsx, src/components/Tabs/TabsNavButton/TabsNavButton.st.css, src/components/Tabs/TabsNavButton/TabsNavButton.tsx
=> Tabs some bug fixes

src/components/Pagination/Pagination.driver.ts, src/components/Pagination/Pagination.spec.tsx, src/components/Pagination/Pagination.st.css, src/components/Pagination/Pagination.tsx, src/components/Pagination/docs/Examples.tsx
This PR adds mobile mode support to `Pagination` component
=> Render Pagination in compact mode for mobile devices

.wuf/generator/templates/mobile/Component/docs/examples.ts, src/components/Card/docs/examples.ts, stories/utils/allComponents.tsx
=> use a component instead of the provider directly in examples

.wuf/generator/templates/desktop/Component/Component.visual.tsx, .wuf/generator/templates/mobile/Component/Component.visual.tsx, applitools.config.js, src/components/Avatar/Avatar.visual.tsx, src/components/AvatarGroup/AvatarGroup.visual.tsx, src/components/Badge/Badge.visual.tsx, src/components/Checkbox/Checkbox.visual.tsx, src/components/Counter/Counter.visual.tsx, src/components/IconButton/IconButton.visual.tsx, src/components/IconToggle/IconToggle.visual.tsx, src/components/LikeButton/LikeButton.visual.tsx, src/components/Pagination/Pagination.visual.tsx, src/components/Ratings/Ratings.visual.tsx, src/components/Tabs/Tabs.visual.tsx, src/components/TextArea/TextArea.visual.tsx, src/components/TextButton/TextButton.visual.tsx, src/components/Toast/Toast.visual.tsx, test/visual/VisualContainerElement.tsx, test/visual/VisualTestContainer.tsx, test/visual/dataHooks.js
=> Visual hook

src/components/Button/Button.st.css, src/components/Button/Button.tsx, src/components/Button/docs/ButtonExtendedExample.tsx
The fourth button style as per https://zeroheight.com/7sjjzhgo2/p/9607e0/t/6042
(secondary, color-5)
=> Add basic secondary default button style

package.json
same as wix-ui, so users won't get multiple stylable versions
=> Infra: upgrade to @stylable/dom-test-kit@1

package.json, src/assets/icons/CheckSuccess.svg, src/assets/icons/index.ts, src/components/Button/docs/ButtonExtendedExample.tsx, src/components/Button/docs/ButtonExtendedWithStyleParamsExample.tsx, src/components/Dropdown/DropdownError.tsx, src/components/ErrorMessageWrapper/ErrorMessageWrapper.tsx, src/components/Grid/docs/examples.ts, src/components/Input/docs/InputExtendedExample.tsx, src/components/LikeButton/LikeButton.driver.ts, src/components/Tabs/TabsNavButton/TabsNavButton.tsx, src/components/Tabs/docs/TabsExtendedExample.tsx, src/components/Text/docs/TextExtendedExample.tsx, src/components/TextButton/docs/TextButtonWithStylesExample.tsx, src/components/TextButton/docs/TextButtonWithStylesMobileExample.tsx, src/components/TextField/TextField.driver.ts, src/components/TextField/TextField.spec.tsx, src/components/TextField/TextField.tsx, src/components/TextField/docs/TextFieldExtendedExample.tsx, src/components/TextField/docs/examples.ts, src/components/TextField/docs/index.story.tsx
@jonathanadler add SuccessIcon to textField component
=> add SuccessIcon to textField component

src/components/TextArea/TextArea.tsx, src/components/TextField/TextField.tsx
=> fix error tooltip position

src/assets/icons/index.ts, stories/utils/allComponents.tsx
=> add icons to allComponents for storybook

src/components/Tabs/Tabs.tsx
Buttons aren't appearing and disappearing on scroll
=> Fix tabs scroll on mobile

src/components/Counter/Counter.driver.ts, src/components/Counter/Counter.meta.tsx, src/components/Counter/Counter.spec.tsx, src/components/Counter/Counter.st.css, src/components/Counter/Counter.tsx, src/components/Counter/docs/index.story.tsx
=> Counter component - Improve aria UX - issue #257

src/components/Counter/Counter.driver.ts, src/components/Counter/Counter.spec.tsx
A Counter driver should accept a typed-in value
=> Counter should accept a typed value

src/assets/icons/ChevronLeft.svg, src/assets/icons/ChevronRight.svg, src/common/animations.ts, src/components/Tabs/ScrollableTabs/ScrollableTabs.st.css, src/components/Tabs/ScrollableTabs/ScrollableTabs.tsx, src/components/Tabs/Tabs.e2e.ts, src/components/Tabs/Tabs.st.css, src/components/Tabs/Tabs.tsx, src/components/Tabs/Tabs.visual.tsx, src/components/Tabs/TabsNavButton/TabsNavButton.tsx, src/components/Tabs/constants.ts, src/components/Tabs/dataHooks.ts, src/components/Tabs/docs/index.story.tsx, src/test/utils.tsx
changes behaviour of navigation scrolling (button and tab click)
+ fixes rtl issues
@johannaasseraf
=> Tabs scroll fix

src/components/SectionNotification/SectionNotification.st.css, src/components/SectionNotification/docs/examples.ts, src/components/SectionNotification/docs/index.story.tsx
@alexkronenberg I think we still need to change the icon's svg
You said it should be 16px but it;s around 15px
=> fix story examples + import string + fix margins

src/components/Button/Button.st.css
Updated hover opacities for buttons to be 0.7
@jonathanadler
=> <Button/> - update hover opacity to 0.7

src/components/Toast/Toast.st.css
changed <Toast/> colors to be more accessible
@jonathanadler
=> <Toast/> - change colors to be more accessible

src/components/Dropdown/Dropdown.driver.ts, src/components/Dropdown/Dropdown.spec.tsx, src/components/Dropdown/DropdownBase.tsx, src/components/StatesButton/StatesButton.st.css
@jonathanadler  please take a look :)
=> style fixes for states button

src/components/DotNavigation/DotNavigation.st.css, src/components/DotNavigation/DotNavigation.tsx
=> <DotNavigation/> - fix dots sizes and alignment

src/components/Counter/Counter.st.css, src/components/Counter/Counter.tsx, src/components/IconButton/IconButton.st.css, src/components/IconButton/IconButton.tsx
=> <Counter/> - add hover and focus behavior

src/components/Dropdown/Dropdown.st.css, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/DropdownOption.tsx
Made it possible to override dropdownOption classes through stylable.
=> fix: Dropdown - expose dropdownOption in stylable

src/components/Counter/Counter.st.css, src/components/Counter/Counter.tsx, src/components/IconButton/IconButton.st.css, src/components/IconButton/IconButton.tsx
This reverts commit b100d3b4b55a57e286ddf802b7700fb427b7024d.
=> Revert "fix: Counter - add missing hover and focus behaviour "

src/components/Counter/Counter.driver.ts, src/components/Counter/Counter.spec.tsx, src/components/Counter/Counter.tsx
https://jira.wixpress.com/browse/EE-24013
=> Counter - a11y fixes

src/components/Dropdown/Dropdown.driver.ts, src/components/Dropdown/Dropdown.meta.tsx, src/components/Dropdown/Dropdown.spec.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/DropdownBase.tsx
Add aria-activedescendant, replace `aria-haspopup` with `role=listbox`, add `contentId` to the core dropdown.
=> Dropdown | Making a11y adjustments

src/components/Dropdown/Dropdown.spec.tsx, src/components/Dropdown/Dropdown.tsx
Motivation
--
Can be used for BI events tracking
=> feat(Dropdown): exposed onExpandedChange prop

src/components/ColorPicker/ColorPicker.driver.ts, src/components/ColorPicker/ColorPicker.visual.tsx, src/components/ColorPicker/ColorPickerItem/ColorPickerItem.driver.ts, src/components/ColorPicker/ColorPickerItem/ColorPickerItem.spec.tsx, src/components/ColorPicker/ColorPickerItem/ColorPickerItem.st.css, src/components/ColorPicker/ColorPickerItem/ColorPickerItem.tsx, src/components/ColorPicker/ColorPickerItem/MobileTooltip.tsx, src/components/ColorPicker/ColorPickerItem/tooltipCommonProps.ts, src/components/ColorPicker/dataHooks.ts, src/components/ColorPicker/docs/ColorPickerExtendedExample.tsx, src/components/ColorPicker/docs/ColorPickerMobileTooltipExample.tsx, src/components/ColorPicker/docs/index.story.tsx
https://zeroheight.com/695j65912/p/07a775-add-to-cart-on-gallery/b/19a09e
=> feat: add disabled and tooltip props to ColorPickerItem

src/components/ColorPicker/ColorPicker.spec.tsx, src/components/ColorPicker/ColorPickerItem/ColorPickerItem.driver.ts, src/components/ColorPicker/ColorPickerItem/ColorPickerItem.spec.tsx, src/components/ColorPicker/ColorPickerItem/ColorPickerItem.tsx
Also other minor errors fixes.
Please release after merge.
=> fix getItemAt in ColorPickerDriver

src/assets/icons/Camera.svg, src/assets/icons/index.ts, src/components/Badge/Badge.st.css, src/components/Badge/Badge.tsx, src/components/Badge/docs/examples.tsx
@johannaasseraf
Would appreciate a review 🙏
=> fix Camera icon + fix badge padding issue with icon

src/components/Autocomplete/Autocomplete.tsx, tslint.json, tslint_base.json
Use solution posted here:
https://github.com/prettier/tslint-config-prettier/issues/280#issuecomment-468116804
=> Fix lint conflict with prettier.

src/components/ActionsMenuLayout/ActionsMenuLayout.driver.ts, src/components/ActionsMenuLayout/ActionsMenuLayout.spec.tsx, src/components/ActionsMenuLayout/ActionsMenuLayout.tsx, src/components/ActionsMenuLayout/Item/ActionsMenuLayoutItem.st.css, src/components/ActionsMenuLayout/Item/ActionsMenuLayoutItem.tsx, src/components/ActionsMenuLayout/docs/ActionsMenuLayoutExtendedExample.tsx
This PR implements this issue: https://github.com/wix/wix-ui-tpa/issues/401
As far as this component is meant to be in `Popover` element we can focus `item` on `cdm` phase
=> <ActionsMenuLayout /> - add keyboard arrow navigation 

src/components/FloatingDropdown/FloatingDropdown.tsx
apparently these need to be imported explicitly
=> FloatingDropdown: import missing styles from Dropdown

src/components/Dialog/Dialog.st.css
I'll add an `rtl` example tomorrow
=> Dialog.st.css added missing rtl declaration

src/components/Dropdown/Dropdown.st.css, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/Dropdown.visual.tsx, src/components/Dropdown/DropdownNativeSelect.tsx, src/components/Dropdown/DropdownOption.tsx, src/components/Dropdown/docs/examples.ts, src/components/Dropdown/docs/index.story.tsx, src/components/Dropdown/helpers.ts, src/components/FloatingDropdown/FloatingDropdown.st.css, src/components/FloatingDropdown/FloatingDropdown.tsx, src/components/FloatingDropdown/FloatingDropdownBase.tsx, src/components/FloatingDropdown/docs/examples.ts, src/components/FloatingDropdown/docs/index.story.tsx, src/components/FloatingDropdown/test-props.ts
Added support for a divider in the Dropdown and FloatingDropdown components
=> Dropdown + FloatingDropdown divider

package.json
…3.9.1 until they will fix the bug.
=> set the applitools/eyes-storybook version to be a fixed version

src/components/Tabs/Tab/Tab.tsx
https://jira.wixpress.com/browse/GROUP-2601
=> added aria-hidden for Tabs empty divs

src/components/Avatar/Avatar.visual.tsx, src/components/AvatarGroup/AvatarGroup.visual.tsx
Will create a fix in a different PR
=> comment out avatar & avatargroup visual tests

stories/utils/SettingsPanel.tsx
=> docs: fix broken Settings Panel code examples

src/components/TextField/TextField.tsx
Didn't write tests, as I checked the tests for errorMessage and I didn't find anything relevant (except for a single one that checks its data hook, but I don't think it's relevant here). Please tell me if I'm wrong.
=> TextField: errorTooltipMaxWidth

docs/RTL.md, docs/USAGE.md, stories/Introduction.tsx
This PR explains what's RTL and how to use it as a consumer.
You can see a readable version here:
https://github.com/wix/wix-ui-tpa/blob/84e5d7baf69110a12056cfaa269265fa4233b887/docs/RTL.md
=> docs: explain how to use RTL

.wuf/generator/templates/Component/docs/index.story.tsx, src/components/ActionsMenuLayout/docs/index.story.tsx, src/components/AddItem/docs/index.story.tsx, src/components/CalendarPopover/docs/index.story.tsx, src/components/Dialog/docs/index.story.tsx, src/components/Event/docs/index.story.tsx, src/components/Pagination/docs/index.story.tsx, src/components/Tabs/docs/index.story.tsx, src/components/Tags/docs/index.story.tsx, src/components/TextArea/docs/index.story.tsx, src/components/index.ts, stories/helperComponents/storyComponent.tsx
create storyComponent for supporting the rtl toggle
use it in existing component stories
and add it to the generator
=> Make rtl toggle work with the TPAComponentsProvider

src/components/IconButton/IconButton.st.css, src/components/IconButton/IconButton.tsx
Caused when I made changes to the IconButton in the Dialog PR
=> fix broken TextField

src/components/Button/Button.st.css, src/components/Button/Button.tsx, src/components/Button/Button.visual.tsx, src/components/Button/docs/ButtonExtendedWithStyleParamsExample.tsx, src/components/Button/docs/index.story.tsx
Fix for https://jira.wixpress.com/browse/DSM-1136
=> Upgraded button icon alignment fix

src/components/FloatingDropdown/FloatingDropdown.st.css, src/components/FloatingDropdown/FloatingDropdown.tsx, src/components/FloatingDropdown/FloatingDropdownBase.st.css, src/components/FloatingDropdown/FloatingDropdownBase.tsx, src/components/FloatingDropdown/docs/FloatingDropdownWiringExample.st.css, src/components/FloatingDropdown/docs/FloatingDropdownWiringExample.tsx, src/components/FloatingDropdown/docs/index.story.tsx
open FloatingDropdown for css overrides
fix label color
=> <FloatingDropdown/> - enabled css overrides

src/components/Toast/Toast.st.css, src/components/Toast/Toast.tsx, src/components/Toast/docs/index.story.tsx
Fixes https://jira.wixpress.com/browse/DSM-1135
=> fix Toast component close button alignment

src/components/Button/Button.st.css, src/components/Button/Button.tsx, src/components/Button/Button.visual.tsx, src/components/Button/docs/ButtonExtendedWithStyleParamsExample.tsx, src/components/Button/docs/index.story.tsx
This reverts commit 459580f2d9bb372a852dff2b1b89323ca929c1f2.
=> Revert "fix(Button): Fix prefix and suffix alignments"

.wuf/generator/codemods/index.js, .wuf/generator/codemods/perfer-config-file.js
This PR adds a codemod that allows initializing a default threshold when creating a new component using the generator.
It looks like this:
=> build(Perfer) - add codemod for generator

src/components/Button/Button.st.css
=> forgot to add fallback on regular background color rule

CHANGELOG.md, package.json, src/components/Button/Button.st.css
Reverting SmartContrast - causing viewer servers to crash
=> remove use of smartContrast

CHANGELOG.md, package.json
=> release: v2.13.2

package.json, src/components/RadioButton/RadioButton.driver.ts, src/components/RadioButton/RadioButton.e2e.ts, src/components/RadioButton/RadioButton.spec.tsx, src/components/RadioButton/RadioButton.st.css, src/components/RadioButton/RadioButton.tsx, src/components/RadioButton/dataHooks.ts, src/components/RadioButton/docs/RadioButtonTestStory.tsx, src/components/RadioButton/docs/examples.ts, stories/index.tsx
[EE-27556] manage focus state and add focusRing if needed - wix-ui-tpa/RadioButton component
=> [EE-27556] manage focus state and add focusRing if needed - wix-ui-tpa/RadioButton component

src/components/Dropdown/Dropdown.st.css
https://jira.wixpress.com/browse/DSM-1353
...
=> set error background color to be important

perfer.config.js, src/components/Checkbox/Checkbox.st.css, src/components/RadioButton/RadioButton.st.css, src/components/RadioButton/docs/RadioButtonTestStory.tsx
This is most noticeable in the box theme height, it was 58px and now is 50px, same as in the design guide
=> fix(RadioButton, Checkbox): Fix height

.storybook/config.js
For consumers using OSX's dark mode
=> fix storybook light theme

src/components/DatePicker/DatePicker.st.css, src/components/DatePicker/DatePicker.visual.tsx, src/components/DatePicker/docs/DatePickerWiringExample.st.css, src/components/DatePicker/docs/examples.ts, src/components/DatePicker/docs/index.story.tsx, src/components/DatePickerInput/DatePickerInput.st.css
Change the width of the DatePicker for responsive width
...
...
...
=> feat(DatePicker) : change for responsive width

src/components/FloatingDropdown/FloatingDropdown.st.css, src/components/FloatingDropdown/FloatingDropdown.visual.tsx, src/components/FloatingDropdown/FloatingDropdownBase.st.css, src/components/FloatingDropdown/FloatingDropdownBase.tsx, src/components/FloatingDropdown/docs/examples.ts, src/components/FloatingDropdown/docs/index.story.tsx
Currently max-width is 20vw, which doesn't work well for mobile.
This PR fixes this issue, and keeps ellipsis behaviour intact
...
https://wix.slack.com/archives/CJRU3U97A/p1608802553336300
...
=> Floating dropdown max-width and ellipsis fix

CHANGELOG.md, package.json
=> release: v2.15.0

src/components/FloatingDropdown/FloatingDropdown.st.css, src/components/FloatingDropdown/FloatingDropdown.tsx, src/components/FloatingDropdown/FloatingDropdown.visual.tsx, src/components/FloatingDropdown/FloatingDropdownBase.st.css, src/components/FloatingDropdown/FloatingDropdownBase.tsx, src/components/FloatingDropdown/docs/examples.ts, src/components/FloatingDropdown/docs/index.story.tsx
=> Adding 'displayBlock' prop to FloatingDropdown component

package.json
=> Concurrent build

CHANGELOG.md, package.json
=> release: v2.16.0

CHANGELOG.md, package.json
=> release: v2.16.1

src/components/Button/Button.st.css, src/components/Button/Button.tsx, src/components/Button/docs/ButtonExtendedWithStyleParamsExample.tsx, src/components/Dropdown/DropdownBase.st.css, src/components/Dropdown/DropdownBase.tsx, src/components/Dropdown/DropdownNativeSelect.st.css, src/components/Dropdown/DropdownNativeSelect.tsx, src/components/Dropdown/DropdownOption.tsx
=> remove default button priority and size

src/components/temp.visual.tsx
=> Add test to break so that I can show applitools

src/components/Tabs/Tab/Tab.st.css, src/components/Tabs/Tab/Tab.tsx, src/components/Tabs/Tabs.meta.tsx, src/components/Tabs/Tabs.visual.tsx, src/components/Tabs/docs/examples.tsx, src/components/Tabs/docs/index.story.tsx
Allow tabs to contain <a> tags for better SEO.
Improves SEO.
-
=> <Tabs />: change span to link if href is provided for better SEO

applitools.config.js, package.json
Trying to control browser version in applitools
...
https://wixeyes.applitools.com/app/test-results/00000251792465730209/?accountId=mE99eP8CUn9UTSXSv98L3OSaJ0NZmAcY6Wndx6WSHODdY110
...
=> use one version back of chrome in eyes-storybook

.storybook/stylable-metadata-plugin.js
=> fix npm run start errors

package.json
Remove axios dependency - it's not used in the library
...
Seems to have a vulnerability
...
=> remove axios

documentation.yaml
Fixed WixDoc contribution md file ref - it was a broken link
I want dev to contribute & discover the project via WixDocs
=> fix contribution md ref

src/components/TextField/TextField.st.css
=> fix(TextField): fix the breaking suffix icon

package.json, src/components/Image/Image.st.css, src/components/Image/Image.tsx, src/components/Image/Image.visual.tsx, src/components/Image/docs/examples.ts, src/components/Image/docs/index.story.tsx
This PR implements resizing options for `Image`.
Depends on https://github.com/wix/wix-ui/pull/2004, so we need to merge that one first.
=> Image - support resizing

CHANGELOG.md, package.json
=> release: version 2.17.0

src/components/TextField/TextField.tsx
=> Adding placement prop to TextField component

src/components/Tooltip/Tooltip.tsx
=> Tooltip component - Adding default value to Max width

src/components/Dropdown/Dropdown.visual.tsx, src/components/Dropdown/DropdownBase.st.css
https://jira.wixpress.com/browse/DSM-1433
=> Dropdown fix dsm 1433

src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/DropdownNativeSelect.tsx, src/components/FloatingDropdown/FloatingDropdownBase.tsx
=> get name from props + add name to dropdown to align props

CHANGELOG.md, package.json
=> release: v2.18.0

package.json, src/components/DatePicker/DatePicker.st.css, src/components/DatePicker/DatePicker.visual.st.css, src/components/DatePicker/DatePicker.visual.tsx, src/components/DatePicker/docs/DatePickerWiringExample.tsx, src/components/DatePicker/docs/index.story.tsx
=> feat(DatePicker): Adaptive to font change

CHANGELOG.md, package.json
=> release: version 2.19.0

src/components/DatePicker/DatePicker.tsx
=> fix(DatePicker): remove the auto focus

src/components/DatePicker/DatePicker.st.css, src/components/DatePicker/DatePicker.visual.st.css, src/components/DatePicker/DatePicker.visual.tsx
=> fix(DatePicker): change the hover circle according to the border radius

README.md, docs/CONTRIBUTION.md
Adjust url's to new monorepo WSR
=> fix wsr links

docs/HOW_TO_OVERRIDE_STYLES_PROPERLY.md, docs/USAGE.md, stories/Introduction.tsx
=> add "how to override styles properly" document

src/components/DatePicker/DatePicker.st.css, src/components/Image/Image.st.css, src/components/Image/Image.tsx
=> Fix stylable warnings

perfer.config.js, src/components/BoxSelection/BoxSelection.driver.ts, src/components/BoxSelection/BoxSelection.meta.tsx, src/components/BoxSelection/BoxSelection.spec.tsx, src/components/BoxSelection/BoxSelection.st.css, src/components/BoxSelection/BoxSelection.tsx, src/components/BoxSelection/BoxSelection.visual.tsx, src/components/BoxSelection/Option.st.css, src/components/BoxSelection/Option.tsx, src/components/BoxSelection/dataHooks.ts, src/components/BoxSelection/docs/BoxSelectionWiringExample.st.css, src/components/BoxSelection/docs/BoxSelectionWiringExample.tsx, src/components/BoxSelection/docs/examples.ts, src/components/BoxSelection/docs/index.story.tsx, src/components/BoxSelection/index.tsx, src/components/index.ts, stories/index.tsx
=> <BoxSelection /> - contribute new component

.wuf/testkits/definitions.js, perfer.config.js, src/components/Popover/Popover.driver.ts, src/components/Popover/Popover.meta.tsx, src/components/Popover/Popover.protractor.driver.ts, src/components/Popover/Popover.spec.tsx, src/components/Popover/Popover.st.css, src/components/Popover/Popover.tsx, src/components/Popover/Popover.visual.tsx, src/components/Popover/constants.ts, src/components/Popover/docs/PopoverWiringExample.st.css, src/components/Popover/docs/PopoverWiringExample.tsx, src/components/Popover/docs/examples.ts, src/components/Popover/docs/index.story.tsx, src/components/Popover/index.tsx, src/components/index.ts, stories/index.tsx
[Popover component](https://docs.google.com/document/d/1SUCddmcECr3n2hoTAryQa5fd3Am7Tp_EOaRgV4Nff4I/edit#) implementation
=> Popover component

perfer.config.js, src/components/RadioButton/RadioButton.e2e.ts, src/components/RadioButton/docs/RadioButtonTestStory.tsx
Even though I removed the e2e test run
=> fix RadioButton e2e test

src/components/TextArea/TextArea.e2e.ts, src/components/TextArea/TextArea.tsx, src/components/TextArea/docs/TextAreaTestStory.tsx, stories/index.tsx
=> TextArea maxlength prop

src/components/Image/Image.st.css, src/components/Image/Image.tsx, src/components/Image/Image.visual.tsx, src/components/Image/docs/examples.ts, src/components/Image/docs/index.story.tsx, src/components/Image/types.ts
This PR implements a `fluid` prop supporting adaptive mode for the image when it's containing inside a layout. Based on Restaurants' solution.
It's need for https://github.com/wix-private/restaurants/pull/1113.
=> Image - implement `fluid` prop

src/components/Image/Image.tsx, src/components/Image/ImageUtils.spec.tsx, src/components/Image/ImageUtils.tsx
This PR fixes a couple of issues found during the integrating and related to the dimension calculation logic.
It's need for wix-private/restaurants#1113.
=> Image - fix dimension calculation issues

CHANGELOG.md, package.json
=> release: version 2.20.0

src/components/RadioButton/docs/RadioButtonWiringExample.tsx
Added a `Box` theme example to the `"Settings Panel"` RadioButton storybook page
=> add box theme to radio button settings panel example

.storybook/config.js, stories/index.ts, stories/storyHierarchy.ts, stories/testStories.ts
=> Fix storybook sidebar sorting again - sorry 

.wuf/generator/codemods/index.js
=> generator: fix codemod for adding an entry for the story file

src/components/TextButton/docs/examples.tsx
=> <TextButton/> - improve story examples

src/components/Image/Image.driver.ts, src/components/Image/Image.st.css, src/components/Image/Image.tsx, src/components/Image/Image.visual.tsx, src/components/Image/docs/examples.ts, src/components/Image/docs/index.story.tsx, src/components/Image/types.ts
This PR adds a new prop called `hoverEffect` supporting two vales (`zoom` & `darken`) according to the spec.
=> Image - implement hover effects

src/components/TextButton/TextButton.st.css
=> change hover opacity to 70% on TextButton

package.json, stories/helperComponents/MockSettings.tsx
=> add color opacity support in storybook settings panel

CHANGELOG.md, package.json
=> release: v2.21.0

CHANGELOG.md, package.json, src/components/Badge/Badge.st.css, src/components/Counter/Counter.st.css, src/components/Dropdown/Dropdown.st.css, src/components/Tag/Tag.st.css
=> Remove extra semilcolons

CHANGELOG.md, package.json, src/components/Dropdown/Dropdown.st.css
=> release: v2.21.2
