wix/wix-ui-tpa

package.json
bump "wix-storybook-utils" version to ^2.0.0 latest wix-style-react version no longer support TextLink
=> infra: update package.json

src/components/Card/Card.driver.ts, src/components/Card/Card.spec.tsx, src/components/Card/Card.st.css, src/components/Card/Card.tsx, src/components/Card/docs/index.story.tsx, src/components/OverlappingCard/OverlappingCard.spec.tsx, src/components/OverlappingCard/OverlappingCard.st.css, src/components/OverlappingCard/docs/index.story.tsx
when card or overlappingCard do not receiving media the info container should spread to take the whole available space
=> card without media

src/components/Tabs/Tabs.st.css
Hi Shlomi,
We want to disable the alignment if we are in rtl , since the alignment is controlled by the user from settings.
=> rtl ignore to tabs alignment

src/components/Tabs/Tabs.st.css
Hi Shlomi/Jonathan,
We need to apply opacity only on the default border color. I made the changes, can you please check ?
=> Tabs Menu - Change the divider color opacity

src/components/Card/mixins.st.css
there's a breaking change in wix-style-processor with renaming the calc function to calculator
=> fix braking change from wix-style-processor

package.json, src/components/Button/Button.st.css, stories/Button/ButtonExtendedExample.st.css
I bumped major because this is a breaking change for current button users.
we already have the `px` part saved in the styleParams so we can't have it added in the library too which will result invalid css like `2pxpx`
=> don't add "px" to border radius

src/components/StripCard/StripCard.st.css
should not break eyes, default border width is 0
=> fix StripCard border color always apply opacity on TPA overrides

.storybook/config.js, stories/index.tsx, webpack.config.storybook.js
hack wix-style-processor to fix hmr problems in storybook when changing st.css files
Problem is happening because of this line:
https://github.com/wix/wix-style-processor/blob/cf38dd80ba3e0b142b25b4313a42d6a7f9baede2/src/styleUpdater.ts#L25
Which causes `wix-style-processor` to ignore changes to style tags
plus
I had to add a timeout to let `wix-style-processor` run after hmr runs
=> fix wix-style-processor hmr problems in storybook

src/components/Tabs/Tabs.st.css
fixing critical error with tabs before pseudo element
=> tabs - fix :before selector

src/components/Tabs/Tabs.tsx
Currently half of our bundle size is `wix-ui-icons-common`.
Its because of way if icons import in `Tabs` component.
This PR use direct icons import to prevent bundling all of them.
=> Fix icon import from `wix-ui-icons-common`

src/components/Autocomplete/Autocomplete.driver.ts, src/components/Autocomplete/Autocomplete.protractor.driver.ts, src/components/Button/Button.driver.ts, src/components/IconToggle/IconToggle.driver.ts, src/components/IconToggle/IconToggle.protractor.driver.ts, src/components/Input/Input.driver.ts, src/components/Input/Input.protractor.driver.ts, src/components/Pagination/Pagination.driver.ts, src/components/Pagination/Pagination.protractor.driver.ts, src/components/StatesButton/StatesButton.driver.ts, src/components/TextButton/TextButton.driver.ts, src/components/TextField/TextField.driver.ts, src/components/TextField/TextField.protractor.driver.ts, src/components/Tooltip/Tooltip.driver.ts, src/components/Tooltip/Tooltip.protractor.driver.ts
as I described privately, this should is neccessary now for testkit
documentation to work.
it should be a temporary change until [this template](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/.wuf/testkits/vanilla.template.ejs#L15) is doing better work than `...require()`
=> chore(*): use direct path to wix-ui-core drivers

webpack.config.storybook.js
This addition will allow testkit tabs to display appropriate import example
closes #148
=> docs(testkit/*): add testkit import examples

src/components/Avatar/Avatar.tsx
@jonathanadler
Hey,
it's a fix for Avatar when no image src is provided.
If anything is passed to imgProps in wix-ui-core's Avatar, even if src is undefined, it tries to load an image with src '/undefined', producing a bad request.
=> Fix Avatar when no src was provided

src/components/Counter/Counter.driver.ts, src/components/Counter/Counter.spec.tsx, src/components/Counter/Counter.st.css, src/components/Counter/Counter.tsx, src/components/Counter/docs/index.story.tsx
This PR contains changes to Counter component. 
changes include: a tooltip that is shown if the user chooses to show an error message while the component is in error state.
Related jira [here](https://jira.wixpress.com/browse/EE-21892)
=> #EE-21892|Counter Component Missing Error States

src/components/StatesButton/StatesButton.st.css, src/components/StatesButton/StatesButton.tsx
This PR was created because of a bug in the StatesButton - If you set the button's font through settings, and select an underline decoration, it won't show because of the inner StatesButton hierarchy, which puts the button's text inside a div.
=> States button remove div

src/components/Tabs/Tabs.tsx
After deep investigation, I’ve discovered that the **componentDidUpdate** method in wix-ui-tpa **tabs** was called recursively in Microsoft Edge and IE.
I’ve found that for some reason the error occurs when the user scrolls to the end of the bar, and it seems to be related with the disappearing of the navigational arrows. I’ve increased the value of SCROLL_EPSILON which seems to fix it. can you review the changes? the value 15 was chosen since it is the width of the arrow, and seems to provide the smoothest behavior.
=> #SCHED-14809 | fix (wix-ui-tpa) prevent recursive calls to componentDidMount

src/components/Badge/Badge.st.css, src/components/Badge/Badge.tsx, src/components/Badge/README.md, src/components/Badge/docs/index.story.tsx
Changed Badge default colors according to https://www.notion.so/Update-Default-Badge-Wiring-in-Storybook-540ac22d87e84892a337eb842a4207c1.
@jonathanadler
=> <Badge/> - change default colors

src/components/Checkbox/Checkbox.tsx, src/components/DotNavigation/DotNavigation.tsx, tsconfig.json
I am working on reducing our bundle size and have noticed that in `wix-ui-tpa` there are few things that could be optimized. Namely `wix-ui-icons-common` and `lodash`
my suggestions work for `wix-ui-icons-common` but, sadly not for `lodash` (maybe add it to externals?)
Before 
After
=> few size optimizations

src/components/Dropdown/Dropdown.tsx
Add flip, fixed and moveBy props, in order to pass them to CoreDropdown.
=> feat(Dropdown): Add 2 CoreDropdown props to Dropdown

src/components/CalendarCell/CalendarCell.st.css
if a type was only "today" with the current prop set to true, date color didn't got the today color
=> fix time type styles priorities

src/components/ColorPicker/ColorPicker.st.css, src/components/ColorPicker/ColorPicker.tsx, src/components/ColorPicker/ColorPickerItem/ColorPickerItem.tsx, src/components/ColorPicker/docs/ColorPickerMobileTooltipExample.tsx
Now color options are highlighted even in disabled state. Should be not.
Also disable hover in mobile mode.
=> Remove hover in mobile mode for ColorPicker

src/components/Dialog/Dialog.tsx
This import added all icons to our bundle. I think other components should not use imports from index too.
=> Fix dialog icon import

src/components/Counter/Counter.st.css
Currently the counter looks like that on IE11: ![image](https://user-images.githubusercontent.com/6060495/97804480-eafbc380-1c58-11eb-9450-8c8e47c1d8a7.png)
It seems that flex-grow isn't supported well on IE11.
This is how it looks after the fix:
=> <Counter> fix layout on IE11

.storybook/addons/FocusRingToggle/index.js, .storybook/addons/FocusRingToggle/register.js, .storybook/addons/FocusRingToggle/shared.js, .storybook/config.js, .storybook/main.js, .storybook/stories.scss, stories/helperComponents/FocusRing.st.css, stories/helperComponents/FocusRing.tsx
This PR simulates the viewer's focus-ring by adding the relevant style globally.
Basically it does what TB does, but the following selector sounds redundant for the StoryBook environment:
`#SITE_CONTAINER.focus-ring-active :not(.has-custom-focus):not(.ignore-focus):focus, #SITE_CONTAINER.focus-ring-active :not(.has-custom-focus):not(.ignore-focus):focus ~ .wixSdkShowFocusOnSibling': {`
It also affects Storybook elements, but I don't think it's an issue. We can restrict it somehow to the component preview if it bothers...
=> docs: simulate focus ring

src/components/Dialog/Dialog.meta.tsx, src/components/Dialog/Dialog.st.css, src/components/Dialog/Dialog.tsx, src/components/Dialog/Dialog.visual.tsx, src/components/Dialog/docs/DialogWiringExample.st.css, src/components/Dialog/docs/DialogWiringExample.tsx, src/components/Dialog/docs/index.story.tsx, src/components/IconButton/IconButton.st.css, src/components/IconButton/IconButton.tsx, src/components/IconButton/docs/IconButtonExtendedExample.st.css, src/components/IconButton/docs/IconButtonExtendedExample.tsx, src/components/IconButton/docs/examples.ts, src/components/IconButton/docs/index.story.tsx, src/components/index.ts, src/test/utils.tsx, src/test/visualTestUtils.ts
This PR is a preliminary fix for https://github.com/wix/wix-ui-tpa/issues/468
At the moment the Dialog component doesn't allow overriding the background color and allowing it to be wired to the site colors.
This PR allows this behaviour, but still leaves the responsibility for passing black and white components to the Dialog, on the TPA's side.
=> Dialog allow style wiring

.swm/1VbSs88wFoa6GAZdNauE.swm, .swm/68LoNKicAoMqrlK2Jyvl.swm, .swm/716IERM4vXmxo7cq5a2H.swm, .swm/dMDxOtdTreBakhqNLBHS.swm, .swm/lTnxX1vvIAcjop54EjNb.swm, .swm/w8m40J8TlaVF5GBLxAgc.swm
This PR adds a complete guide explaining, using `FloatingDropdown`, how to support `overrideStyleParams` based on https://github.com/wix/wix-ui-tpa/pull/503.
These are the units:
=> Swimm - add walkthrough guide for supporting overrideStyleParams

src/components/Checkbox/Checkbox.st.css, src/components/Checkbox/Checkbox.visual.tsx, src/components/Checkbox/docs/examples.ts, src/components/Checkbox/docs/index.story.tsx, src/components/RadioButton/RadioButton.st.css, src/components/RadioButton/RadioButton.visual.tsx, src/components/RadioButton/docs/examples.ts, src/components/RadioButton/docs/index.story.tsx, src/components/RadioButton/index.tsx
This PR solves some bugs that @barboaron from the RichContentEditor team found.
In addition, I added some styles for the Box theme on disabled mode according to this spec: https://zeroheight.com/7sjjzhgo2/p/05a744-05-selections/b/285e96.
The bugs that were fixed:
1. In the checkbox component: fix the box border overlapping issue.
2. In the RadioButton component: Override the styling that comes from the wix-ui-core.
=> feat(RadioButton, Checkbox) - add disabled mode state for theme box and some bug fixes.

src/components/Dialog/Dialog.st.css, src/components/Dialog/Dialog.tsx
I've noticed that my previous work on the Dialog had a bug:
the `wiredToSiteColors` prop only worked when consumers didn't actively pass colors (using st-mixin).
So for instance, if you go to the Dialog settings panel, in our live storybook site, you'll see that once you select colors to override, the toggle doesn't take any effect.
This PR fixes this issue.
=> Dialog: fix not wired state

src/components/TextArea/TextArea.st.css
Use the param of the default background color as a fallback.
...
...
...
=> fix(TextArea) - Use the default backgroundColor param

src/components/RadioButton/RadioButton.tsx
At [#547](https://github.com/wix/wix-ui-tpa/pull/547) the ability to use a children prop instead of label prop was added, and there is intention to deprecate the label prop in the future.
Today we use the value of label prop also for aria-label. I've exposed aria-label as an optional prop so it'd be possible to use the children prop and update 'aria-label' and not to be broken in the future when 'label' would be deprecated.
=> Radio Button - adding optional aria-label prop

src/components/Image/Image.spec.tsx, src/components/Image/Image.tsx, src/components/Image/Image.visual.tsx, src/components/Image/docs/examples.ts, src/components/Image/docs/index.story.tsx
This PR removes `mediaItem` prop and makes `src` to support both absolute and relative sources.
=> Image - make `src` to support absolute and relative

src/components/RadioButton/RadioButton.e2e.ts, src/components/RadioButton/RadioButton.spec.tsx, src/components/RadioButton/RadioButton.tsx, src/components/RadioButton/docs/RadioButtonTestStory.tsx
The desired improvement - changing the focus ring so it'd not appear after every mouse click (only from keyboard).
=> feat(wix-ui-tpa): radio-button don't show focus ring on mouse click

src/components/Image/Image.tsx, src/components/Image/Image.visual.tsx, src/components/Image/docs/examples.ts, src/components/Image/docs/index.story.tsx
This PR implements the aspectRatio prop for `Image`.
We should decide how to manage and infer the dimensions (it's not in the scope of this task but it might change the implementation of `aspectRatio` later).
=> Image - support aspectRatio prop

package.json, src/components/RadioButton/RadioButton.e2e.ts, src/components/RadioButton/RadioButton.tsx, src/components/RadioButton/docs/RadioButtonTestStory.tsx
We'd like to use the radioButton component but we get a focus ring on mobile after a regular tapping which looks odd. 
More details available here -> https://jira.wixpress.com/browse/EE-28048.
...
Using TPAComponentsContext was suggested as a relatively immediate and simple solution. We'd be happy to unblock this problem so we'd be able to use the component.
...
...
=> Radio button remove focus ring on mobile

package.json
Trying to reduce flakiness by moving the unit tests out of the concurrent process, so that we won't have port collisions.
=> "fix" port issue in concurrent tests

stories/Playground/example.tsx
This PR fixes the image in the playground example:
Actually we'd also like to change these places:
https://github.com/wix/wix-ui-tpa/blob/master/src/components/Card/docs/examples.tsx#L3
https://github.com/wix/wix-ui-tpa/blob/master/src/components/Card/docs/index.story.tsx#L37
But I think it's a little early (maybe after the first integration?)
=> fix(Playground): use image media item

src/components/HeroImage/HeroImage.tsx, src/components/ThumbnailImage/ThumbnailImage.tsx
This PR changes the default resize value to `cover` in HeroImage and ThumbnailImage. This is a product decision from @michalvardi , since it would be the case most of the time (according to the product research).
Notice that `contains` still remains the default value in the case of Image, and we think it's okay (the idea is to see the full image in generic cases).
=> Image - change default resize to cover

src/components/Popover/docs/PopoverWiringExample.st.css
This PR fixes the following warning once starting Storybook (it happens only on startup):
```bash
WARNING in Stylable: /Users/nitayn/dev/wix-ui-tpa/src/components/Popover/docs/PopoverWiringExample.st.css:8:24: cannot find native function or custom formatter called color
6 | .root {
7 |   -st-mixin: overrideStyleParams(
>  8 |     BackgroundColor ''"color(--BackgroundOverride)"''
|                        ^
9 |   );
10 | }
```
=> fix(Popover): Stylable warning 

src/components/Badge/Badge.visual.st.css, src/components/CounterBadge/CounterBadge.visual.st.css, webpack.config.storybook.js
Currently, consumers will see this warning once they start using the DatePicker component.
The reason is for incorrect style extending.
We will need to fix it anyway, but this PR makes sure the storybook build will fail (and not just throw warnings)
@sivanharel - please fix the style extending before merging
=> infra - fail storybook build for incorrect stylable usage

.storybook-test/config.js, src/components/Dialog/Dialog.st.css, src/components/Dialog/Dialog.tsx, src/components/Dialog/Dialog.visual.tsx, src/components/Dialog/docs/examples.ts, src/components/Dialog/docs/index.story.tsx, src/test/visualTestWrapper.tsx, stories/utils/MobileExample.st.css, stories/utils/MobileExample.tsx, stories/utils/PixelFrame.tsx
Added ability to have non-fullscreen modals on mobile
https://jira.wixpress.com/plugins/servlet/samlsso?redirectTo=%2Fbrowse%2FDSM-1449
...
Non-fullscreen modal on mobile has vertical constraints -> max height of 440px and minimum top/bottom padding should be 20px. This vertical padding would be needed in edge-cases where screen height would be smaller than possible Dialog component max-height. So to always have vertical padding, added the outer wrapper container for Dialog content.
...
...
=> <Dialog/> - added notFullscreenOnMobile prop for mobile

src/components/RadioButton/RadioButton.st.css
The box border should change from 60% to 100% both on hover and focus.
See comment on [EE-28048](https://jira.wixpress.com/browse/EE-28048?focusedCommentId=8601528&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel)
...
Would like to migrate to radio button at our project.
...
...
=> Radio Button - box border should change from 60% to 100% both on hover and focus

src/components/Image/Image.visual.st.css, src/components/Image/Image.visual.tsx
This PR should fix the flaky tests in Image.
Those are the problematic tests:
- Image/Relative Media URI/with wiring: override background color
- Image/Absolute URL/with wiring: override background color
- Image/Relative Media URI: with onError
- Image/Relative Media URI: with onError
The common for all of them is the usage of `invalidSrc` which triggers the native broken image icon of the browser. The thing is ui-core's Image [replaces](https://github.com/wix/wix-ui/blob/master/packages/wix-ui-core/src/components/image/image.tsx#L113-L116) the source in such cases with an image with dimensions of 1x1 pixels, in order to hide the native icon. Probably sometimes Applitools is fast enough to take the screenshot before that the icon is replaced (I also managed to notice it when running the …
=> Image - fix flaky tests

perfer.config.js, src/components/ActionsMenuLayout/ActionsMenuLayout.driver.ts, src/components/ActionsMenuLayout/ActionsMenuLayout.e2e.ts, src/components/ActionsMenuLayout/ActionsMenuLayout.spec.tsx, src/components/ActionsMenuLayout/ActionsMenuLayout.tsx, src/components/ActionsMenuLayout/ActionsMenuLayout.visual.tsx, src/components/ActionsMenuLayout/dataHooks.ts, src/components/ActionsMenuLayout/docs/ActionsMenuLayoutTestStory.tsx, stories/testStories.ts
Fixes https://jira.wixpress.com/browse/DSM-1138
Currently component always focuses the first element or the one provided with focusedIndex prop on initial load, which is problematic in some use-cases.
Update behaviour will only autofocus if focusedIndex prop is provided. Manual focus is affected by this change - tab focus, arrow key navigation and focus on click are not affected.
Also fixed bug where clicking on list item would not always update internal state, so trying to use arrow keys would focus on the wrong list item.
...
...
...
=> <ActionsMenuLayout /> - fix focus handling
